theme: jekyll-theme-architect
title: Ocean Shores House
description: Brought to you by Zavala/Brume
sidebar-content: If interested just check out the calender for available weekends. Call either, Arthur @ <a href="tel:2539519734">(253) 951-9734</a> or Mike @ <a href="tel:2062251551">(206) 225-1551</a> to book and reserve your stay.
